title: TID's Blog
subtitle: null
description: 每一篇文章都是一种进步，每一句感慨都是一次思考
keywords: null
author: TigerInYourDream
language: zh-CN
timezone: null
url: https://imzy.vip
root: /
permalink: posts/:abbrlink/
permalink_defaults: null
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':title.md'
default_layout: post
titlecase: false
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: null
external_link:
  enable: true
index_generator:
  path: ''
  per_page: 10
  order_by: '-date'
default_category: uncategorized
category_map: null
tag_map: null
date_format: YYYY-MM-DD
time_format: HH:mm:ss
per_page: 10
pagination_dir: page
theme: butterfly
deploy:
  type: git
  repo: https://github.com/TigerInYourDream/blog-source.git
  branch: master
  token: ${{ secrets.GITHUB_TOKEN }}
  name: TigerInYourDream
  email: zyzzz0928@gmail.com
excerpt: null
depth: 1
excerpt_excludes: []
more_excludes: []
hideWholePostExcerpts: true