name: Blog CI/CD

on:
  push:
    branches: [source]
    paths:
      - '*.json'
      - '**.yml'
      - '**/source/**'

# 添加这些权限
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  blog:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    # 添加环境配置
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Cache node_modules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Init Node.js
        run: |
          npm cache clean --force
          npm config set strict-ssl false
          npm install
          echo "init node successful"
      - name: Install Hexo-cli
        run: |
          npm install -g hexo-cli --save
          echo "install hexo successful"
      - name: Build Blog
        run: |
          hexo clean
          hexo g
          touch public/.nojekyll
          echo "build blog successful"
      
      # 替换旧的部署步骤
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      
      - run: echo "Deploy Successful!"
